version: '3'
services:
    php:
        build: 
            context: docker/php-fpm
        restart: always
        volumes:
            - ./docker/php-fpm/configuration/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
            - ./public/:/var/www/html
    db:
        image: postgres:12.3
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./docker/postgres/configuration/:/docker-entrypoint-initdb.d
    web:
        image: nginx
        volumes:
            - ./public/:/var/www/html
            - ./docker/nginx/configuration/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db   
